In [17]:
import numpy as np
z = np.zeros(10)
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [21]:
#[create a array from 10 to 48]
array = np.arange(10, 49)#it`s exclusive
array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

In [43]:
#invert the array
z = np.arange(0,50)
print z
z = z[::-1]
print z

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [45]:
#reshape array into matrix
z = np.arange(9)
z = z.reshape(3,3)
z

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [48]:
#get index of nonzero elements
nonZeroIndex = np.nonzero([1,2,0,2,6,0])
nonZeroIndex

(array([0, 1, 3, 4]),)

In [51]:
#identity matrix
identity = np.eye(3)
identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [56]:
matrix = np.random.random((3,3,3))
matrix

array([[[0.32661094, 0.35832278, 0.61247085],
        [0.02413681, 0.06359972, 0.90684132],
        [0.36966601, 0.95560091, 0.57821119]],

       [[0.30956223, 0.01483522, 0.64292349],
        [0.32468139, 0.23166884, 0.94347734],
        [0.4279421 , 0.48989811, 0.63294715]],

       [[0.39165098, 0.15232138, 0.8262345 ],
        [0.5757325 , 0.18850249, 0.39835139],
        [0.13980882, 0.23571214, 0.76172184]]])

In [59]:
#create a 10x10 random matrix and gets the minimum and maximum
array = np.random.random((10,10))
arrayMax, arrayMin = array.max(), array.min()
print(arrayMax, arrayMin)

(0.9933098706877285, 0.012455240460257921)


In [64]:
#create a vector with 40 elements and get the mean value
vector = np.random.random(30)
print(vector.mean())

0.4532174548411658


In [75]:
#creates a 10x10 array with 0 inside and 1 in the border
array = np.ones((10,10))
array[1:-1, 1:-1] = 0
array

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [78]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


In [81]:
np.info(np.diag)

 diag(v, k=0)

Extract a diagonal or construct a diagonal array.

See the more detailed documentation for ``numpy.diagonal`` if you use this
function to extract a diagonal and wish to write to the resulting array;
whether it returns a copy or a view depends on what version of numpy you
are using.

Parameters
----------
v : array_like
    If `v` is a 2-D array, return a copy of its `k`-th diagonal.
    If `v` is a 1-D array, return a 2-D array with `v` on the `k`-th
    diagonal.
k : int, optional
    Diagonal in question. The default is 0. Use `k>0` for diagonals
    above the main diagonal, and `k<0` for diagonals below the main
    diagonal.

Returns
-------
out : ndarray
    The extracted diagonal or constructed diagonal array.

See Also
--------
diagonal : Return specified diagonals.
diagflat : Create a 2-D array with the flattened input as a diagonal.
trace : Sum along diagonals.
triu : Upper triangle of an array.
tril : Lower triangle of an array.

Examples
--------
>>> x = np.ar

In [88]:
Z = np.diag(1+np.arange(4),k=1)
print(Z)

[[0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]
 [0 0 0 0 0]]


In [92]:
Z = np.zeros((8,8),dtype=int)
#Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [0 0 0 0 0 0 0 0]
 [0 1 0 1 0 1 0 1]
 [0 0 0 0 0 0 0 0]
 [0 1 0 1 0 1 0 1]
 [0 0 0 0 0 0 0 0]
 [0 1 0 1 0 1 0 1]
 [0 0 0 0 0 0 0 0]]


In [93]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


In [94]:
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [96]:
np.info(np.tile)

 tile(A, reps)

Construct an array by repeating A the number of times given by reps.

If `reps` has length ``d``, the result will have dimension of
``max(d, A.ndim)``.

If ``A.ndim < d``, `A` is promoted to be d-dimensional by prepending new
axes. So a shape (3,) array is promoted to (1, 3) for 2-D replication,
or shape (1, 1, 3) for 3-D replication. If this is not the desired
behavior, promote `A` to d-dimensions manually before calling this
function.

If ``A.ndim > d``, `reps` is promoted to `A`.ndim by pre-pending 1's to it.
Thus for an `A` of shape (2, 3, 4, 5), a `reps` of (2, 2) is treated as
(1, 1, 2, 2).

Note : Although tile may be used for broadcasting, it is strongly
recommended to use numpy's broadcasting operations and functions.

Parameters
----------
A : array_like
    The input array.
reps : array_like
    The number of repetitions of `A` along each axis.

Returns
-------
c : ndarray
    The tiled output array.

See Also
--------
repeat : Repeat elements of an array.
br

In [102]:
Z = np.random.random((5,5))
Zmax, Zmin = Z.max(), Z.min()
Z = (Z - Zmin)/(Zmax - Zmin)
print(Z)

[[0.72450796 0.27669398 0.69484567 0.74766213 0.88658127]
 [0.42978657 0.09858111 0.08630599 0.13161879 0.71640482]
 [0.56315719 1.         0.21357588 0.45563588 0.0395665 ]
 [0.         0.42697604 0.29243437 0.32584737 0.46026105]
 [0.74431572 0.51670882 0.40637413 0.93974933 0.06577036]]


In [103]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


In [106]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [109]:
Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] *= -1
print (Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [111]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


In [119]:
Z = np.random.uniform(-10,+10,10)
#uniform creates an array based on the values passed. the first is the lowest boundary, the second is the biggest boundary and the last is the sazy of the array

#np.info(np.random.uniform)
print(Z)
print (np.trunc(Z + np.copysign(0.5, Z)))

[ 3.46443708  0.16148897 -8.85414469  0.80369809 -6.94312187 -7.63008585
 -8.53728872  0.63942404 -7.30995406  3.31194736]
[ 3.  0. -9.  1. -7. -8. -9.  1. -7.  3.]


In [122]:
#extract the integer part of the elements of the array.
Z = np.random.uniform(0,10,10)

print(Z)
print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print (np.trunc(Z))

[4.86145713 1.63212176 0.14377425 8.7050781  0.91692349 5.23562944
 3.24418696 2.92935617 5.84814223 2.04022555]
[4. 1. 0. 8. 0. 5. 3. 2. 5. 2.]
[4. 1. 0. 8. 0. 5. 3. 2. 5. 2.]
[4. 1. 0. 8. 0. 5. 3. 2. 5. 2.]
[4 1 0 8 0 5 3 2 5 2]
[4. 1. 0. 8. 0. 5. 3. 2. 5. 2.]


In [125]:
#create a 5x
Z = np.zeros((5,5))
Z += np.arange(5)


array([0, 1, 2, 3, 4])