In [1]:
import numpy as np
a = np.array([[1,2],[3,4]])

In [3]:
a
print(a.sum(axis=0))
print(a.sum(axis=1))

[4 6]
[3 7]


In [5]:
np.insert(a, 1, 5, axis=1)

array([[1, 5, 2],
       [3, 5, 4]])

In [6]:
np.insert(a, 1, 5, axis=0)

array([[1, 2],
       [5, 5],
       [3, 4]])

In [7]:
#adicionar valores no final de um array
arr = np.array([1,2,3])


In [9]:
np.append(arr, [4,5,6])


array([1, 2, 3, 4, 5, 6])

In [11]:
#deletar elementos
mat = np.array([[1,2],[3,4],[5,6]])
np.delete(mat, 1, 0)

array([[1, 2],
       [5, 6]])

In [13]:
#repetir elementos do array
b = np.array([[1,2],[3,4]])
np.repeat(b,2)

array([1, 1, 2, 2, 3, 3, 4, 4])

In [14]:
#repetir ao longo de um eixo
a = np.array([1,2,3])
np.tile(a,3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [15]:
b = np.array([[1,2],[3,4]])
np.tile(b, 3)

array([[1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4]])

In [16]:
#dividir arrays
a = np.array([[1,2,3],[4,5,6]])
a


array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
np.array_split(a, 2, axis=1)

[array([[1, 2],
        [4, 5]]), array([[3],
        [6]])]

In [19]:
a = np.array([[1,2,3],[4,5,6],[7,8,9], [10,11,12]])
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [20]:
np.array_split(a,2)

[array([[1, 2, 3],
        [4, 5, 6]]), array([[ 7,  8,  9],
        [10, 11, 12]])]

In [21]:
np.zeros(4)

array([0., 0., 0., 0.])

In [23]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [25]:
np.ones((5,5))


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [28]:
#matriz identidade, matriz quadrada
a = np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [29]:
#indexação booleana
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13])
a[a>4]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13])

In [30]:
idx = (a > 3)
idx

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True])